title: Kielipankki training material at CSC

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-sitemap
  - liquid

defaults:
  -
    scope:
      path: "tutorials"
    values:
      layout: "default"
