title: Kielipankki training material at CSC

markdown: CommonMarkGhPages

plugins:
  - jekyll-sitemap
  - liquid
  - kramdown
  - rouge

defaults:
  -
    scope:
      path: "tutorials"
    values:
      layout: "default"
